### ISSUE TITLE
Created pem file but I cannot find it

### ISSUE THREAD

**Issue by BTC415** [dodger213/Trade-Mark-Today#6]
How to find the generated key file?

**Comment by dodger213** [comment]
When you first open OpenSSL command, the default route is C:/users/pc
so you can find on that route

**Comment by dodger213** [comment]
Or you can change route to your project folder
C;/users/pc
cd your-project-folder
then type the command above and the key files are generated on your project folder

**Comment by BTC415** [comment]
Good thanks
